# Generated by Django 5.2.14 on 2026-08-12 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0001_initial'),
    ]

    operations = [
        # Crear el esquema PostgreSQL antes de las tablas
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS validaciones_2026;",
            reverse_sql="DROP SCHEMA IF EXISTS validaciones_2026 CASCADE;",
        ),
        migrations.CreateModel(
            name='ValCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_departamento', models.CharField(blank=True, max_length=20, null=True)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_localidad', models.CharField(blank=True, max_length=20, null=True)),
                ('regional', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_cabecera', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_cabecera', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_area_cabecera', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_cabecera', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_coordinador', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_coordinador', models.EmailField(blank=True, max_length=254, null=True)),
                ('codigo_area_coordinador', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_coordinador', models.CharField(blank=True, max_length=30, null=True)),
                ('cuil_coordinador', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cabecera',
                'verbose_name_plural': 'Cabeceras',
                'db_table': '"validaciones_2026"."cabeceras"',
            },
        ),
        migrations.CreateModel(
            name='ValEstablecimiento',
            fields=[
                ('cueanexo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('escuela', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Establecimiento (Validaciones)',
                'verbose_name_plural': 'Establecimientos (Validaciones)',
                'db_table': '"validaciones_2026"."establecimientos"',
            },
        ),
        migrations.CreateModel(
            name='ValReferenteCargaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Referente de Carga Temporal',
                'verbose_name_plural': 'Referentes de Carga Temporal',
                'db_table': '"validaciones_2026"."referentes_carga_temporal"',
            },
        ),
        migrations.CreateModel(
            name='ValGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cueanexo', models.CharField(max_length=9)),
                ('nombre_grado', models.CharField(choices=[('2do Año/Grado', '2do Grado'), ('3er Año/Grado', '3er Grado')], default='2do Año/Grado', max_length=13)),
                ('estado_carga', models.BooleanField(default=False)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='evaluaciones_educativas.valestablecimiento')),
            ],
            options={
                'verbose_name': 'Grado (Validaciones)',
                'verbose_name_plural': 'Grados (Validaciones)',
                'db_table': '"validaciones_2026"."grados"',
            },
        ),
        migrations.CreateModel(
            name='ValSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seccion', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('Z', 'Z')], max_length=20)),
                ('turno', models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('DOBLE', 'Doble')], max_length=20)),
                ('matricula', models.IntegerField(blank=True, null=True, verbose_name='Matrícula cargada')),
                ('estado_validacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('NO_EXISTE', 'No existe')], default='PENDIENTE', max_length=10, verbose_name='Estado de validación')),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_ultima_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cabecera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='evaluaciones_educativas.valcabecera', verbose_name='Cabecera asignada')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='evaluaciones_educativas.valgrado')),
            ],
            options={
                'verbose_name': 'Sección (Validaciones)',
                'verbose_name_plural': 'Secciones (Validaciones)',
                'db_table': '"validaciones_2026"."secciones"',
                'unique_together': {('seccion', 'grado', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='ValHistorialMatriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_anterior', models.IntegerField(blank=True, null=True)),
                ('matricula_nueva', models.IntegerField()),
                ('justificacion', models.TextField(verbose_name='Justificación del cambio')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario_cambio', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_matriculas', to='evaluaciones_educativas.valseccion')),
            ],
            options={
                'verbose_name': 'Historial de Matrícula',
                'verbose_name_plural': 'Historial de Matrículas',
                'db_table': '"validaciones_2026"."historial_matriculas"',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='ValHistorialCambiosEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(verbose_name='Justificación de por qué no existe')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='evaluaciones_educativas.valseccion')),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Establecimiento',
                'verbose_name_plural': 'Historial de Cambios de Establecimiento',
                'db_table': '"validaciones_2026"."historial_cambios_establecimiento"',
                'ordering': ['-fecha'],
            },
        ),
    ]
