from django.db import migrations


CREATE_DIAGNOSTICO_INGRESO_TABLES = """
CREATE SCHEMA IF NOT EXISTS "diagnostico_ingreso_2026";

CREATE TABLE IF NOT EXISTS "diagnostico_ingreso_2026"."establecimientos" (
    "cueanexo" varchar(9) PRIMARY KEY,
    "escuela" varchar(255) NOT NULL,
    "sector" varchar(255) NOT NULL,
    "ambito" varchar(255) NOT NULL,
    "region" varchar(255) NOT NULL,
    "localidad" varchar(255) NOT NULL,
    "departamento" varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "diagnostico_ingreso_2026"."grados" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" uuid NOT NULL UNIQUE,
    "cueanexo" varchar(9) NOT NULL,
    "nombre_grado" varchar(20) NOT NULL,
    "estado_carga" boolean NOT NULL,
    "Establecimiento_id" varchar(9) NOT NULL,
    CONSTRAINT "diag_ingreso_grado_establecimiento_fk"
        FOREIGN KEY ("Establecimiento_id")
        REFERENCES "diagnostico_ingreso_2026"."establecimientos" ("cueanexo")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "diagnostico_ingreso_2026"."secciones" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" uuid NOT NULL UNIQUE,
    "seccion" varchar(20) NOT NULL,
    "turno" varchar(20) NOT NULL,
    "grado_id" bigint NOT NULL,
    CONSTRAINT "diag_ingreso_seccion_grado_fk"
        FOREIGN KEY ("grado_id")
        REFERENCES "diagnostico_ingreso_2026"."grados" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT "diag_ingreso_seccion_unique"
        UNIQUE ("seccion", "grado_id", "turno")
);

CREATE TABLE IF NOT EXISTS "diagnostico_ingreso_2026"."alumnos" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" uuid NOT NULL UNIQUE,
    "dni" varchar(10) NULL UNIQUE,
    "nombre" varchar(50) NOT NULL,
    "apellido" varchar(50) NOT NULL,
    "comunidad_indigena" varchar(11) NULL,
    "discapacidad" varchar(2) NULL,
    "seccion_id" bigint NULL,
    CONSTRAINT "diag_ingreso_alumno_seccion_fk"
        FOREIGN KEY ("seccion_id")
        REFERENCES "diagnostico_ingreso_2026"."secciones" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "diagnostico_ingreso_2026"."lecturas" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "public_id" uuid NOT NULL UNIQUE,
    "modelo_examen" varchar(1) NOT NULL,
    "fecha_lectura" timestamp with time zone NOT NULL,
    "encargado_carga" varchar(9) NOT NULL,
    "item_1" varchar(1) NOT NULL,
    "item_2" varchar(1) NOT NULL,
    "item_3" varchar(1) NOT NULL,
    "item_4" varchar(1) NOT NULL,
    "item_5" varchar(1) NOT NULL,
    "item_6" varchar(1) NOT NULL,
    "item_7" varchar(1) NOT NULL,
    "item_8" varchar(1) NOT NULL,
    "item_9" varchar(1) NOT NULL,
    "item_10" varchar(1) NOT NULL,
    "item_11" varchar(1) NOT NULL,
    "item_12" varchar(1) NOT NULL,
    "confianza_json" jsonb NULL,
    "revisado_manualmente" boolean NOT NULL,
    "observaciones" text NOT NULL,
    "alumno_id" bigint NULL,
    CONSTRAINT "diag_ingreso_lectura_alumno_fk"
        FOREIGN KEY ("alumno_id")
        REFERENCES "diagnostico_ingreso_2026"."alumnos" ("id")
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("evaluaciones_educativas", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_DIAGNOSTICO_INGRESO_TABLES,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
