# Generated by Django 5.2.14 on 2026-09-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0002_create_diagnostico_ingreso_2026_tables'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secciondiagnostico_ingreso_2026',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='comunidad_indigena',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='discapacidad',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='id',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='ambito',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='cueanexo',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='region',
        ),
        migrations.RemoveField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='Establecimiento',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='cueanexo',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='estado_carga',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='nombre_grado',
        ),
        migrations.RemoveField(
            model_name='gradodiagnostico_ingreso_2026',
            name='public_id',
        ),
        migrations.AddField(
            model_name='alumnodiagnostico_ingreso_2026',
            name='id_alumno',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establecimientosdiagnostico_ingreso_2026',
            name='id_establecimiento',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradodiagnostico_ingreso_2026',
            name='id_grado',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secciondiagnostico_ingreso_2026',
            name='id_seccion',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='secciondiagnostico_ingreso_2026',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='secciondiagnostico_ingreso_2026',
            name='id',
        ),
        migrations.RemoveField(
            model_name='secciondiagnostico_ingreso_2026',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='secciondiagnostico_ingreso_2026',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='secciondiagnostico_ingreso_2026',
            name='turno',
        ),
    ]
