# Generated by Django 5.2.14 on 2026-08-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0002_valcabecera_valestablecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valestablecimiento',
            name='cabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos', to='evaluaciones_educativas.valcabecera', verbose_name='Cabecera asignada'),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='participa_aprender',
            field=models.BooleanField(blank=True, default=None, help_text='None = sin procesar, True = participa, False = no participa', null=True, verbose_name='Participa en Aprender'),
        ),
        migrations.AlterField(
            model_name='valseccion',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('SIN_MATRICULA', 'Sin matrícula'), ('MODIFICADO', 'Modificado')], default='PENDIENTE', max_length=13, verbose_name='Estado de validación'),
        ),
    ]
