# Generated by Django 5.2.14 on 2026-08-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0003_validaciones_establecimientos_participacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valhistorialcambiosestablecimiento',
            name='seccion',
        ),
        migrations.AddField(
            model_name='valhistorialcambiosestablecimiento',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='evaluaciones_educativas.valestablecimiento'),
        ),
        migrations.AlterField(
            model_name='valhistorialcambiosestablecimiento',
            name='justificacion',
            field=models.TextField(verbose_name='Justificación de participación'),
        ),
    ]
