# Generated by Django 5.2.14 on 2026-08-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0004_remove_valhistorialcambiosestablecimiento_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_establecimientos_asociados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_matriculas_por_seccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_secciones_asociadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cod_provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='apellido_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_localidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_provincia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='correo_director',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='nombre_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='telefono_director',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valhistorialcambiosestablecimiento',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_establecimientos_modificados', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga'),
        ),
        migrations.AddField(
            model_name='valhistorialmatriculas',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_matriculas_modificadas', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga'),
        ),
    ]
