# Generated by Django 5.2.14 on 2026-08-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0004_remove_valhistorialcambiosestablecimiento_seccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valseccion',
            name='cabecera',
        ),
        migrations.RemoveField(
            model_name='valseccion',
            name='fecha_ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='valseccion',
            name='usuario_ultima_modificacion',
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_establecimientos_asociados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_matriculas_por_seccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cantidad_secciones_asociadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='cod_provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='valcabecera',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='apellido_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='carga_completa',
            field=models.BooleanField(default=False, help_text='True cuando el referente confirmó que terminó de cargar todas las secciones', verbose_name='Carga completa'),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_localidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='codigo_provincia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='correo_director',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='motivo_no_participa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de no participación'),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='nombre_director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valestablecimiento',
            name='telefono_director',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='valgrado',
            name='grado_creado',
            field=models.BooleanField(default=False, verbose_name='Grado creado manualmente'),
        ),
        migrations.AddField(
            model_name='valhistorialcambiosestablecimiento',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_establecimientos_modificados', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga'),
        ),
        migrations.AddField(
            model_name='valhistorialmatriculas',
            name='referente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_matriculas_modificadas', to='evaluaciones_educativas.valreferentecargatemporal', verbose_name='Referente de Carga'),
        ),
        migrations.AddField(
            model_name='valreferentecargatemporal',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='valseccion',
            name='motivo_deshabilitacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de deshabilitación'),
        ),
        migrations.AddField(
            model_name='valseccion',
            name='seccion_creada',
            field=models.BooleanField(default=False, verbose_name='Sección creada manualmente'),
        ),
        migrations.AlterField(
            model_name='valgrado',
            name='nombre_grado',
            field=models.CharField(choices=[('3er Año/Grado', '3er Año/Grado')], default='3er Año/Grado', max_length=50),
        ),
        migrations.AlterField(
            model_name='valhistorialmatriculas',
            name='matricula_nueva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valseccion',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('SIN_MATRICULA', 'Sin matrícula'), ('MODIFICADO', 'Modificado'), ('DESHABILITADO', 'Deshabilitado')], default='PENDIENTE', max_length=15, verbose_name='Estado de validación'),
        ),
        migrations.AlterField(
            model_name='valseccion',
            name='turno',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('MAÑANA EXTENDIDA', 'Mañana Extendida'), ('TARDE', 'Tarde'), ('TARDE EXTENDIDA', 'Tarde Extendida'), ('DOBLE', 'Doble'), ('VESPERTINO', 'Vespertino')], max_length=20),
        ),
    ]
