# Generated by Django 5.2.14 on 2026-06-04 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0009_tablatemporalalumno_alter_matematica2026_pregunta_11'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoFluidez2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('comunidad_indigena', models.CharField(blank=True, choices=[('QOM', 'Qom'), ('MOQOIT', 'Moqoit'), ('WICHI', 'Wichí'), ('NINGUNA', 'Ninguna')], max_length=11)),
                ('discapacidad', models.CharField(blank=True, choices=[('SI', 'Sí, la persona tiene una discapacidad'), ('NO', 'Ninguna')])),
            ],
            options={
                'db_table': '"fluidez_2026"."alumnos"',
            },
        ),
        migrations.CreateModel(
            name='EstablecimientosFluidez2026',
            fields=[
                ('cueanexo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('escuela', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '"fluidez_2026"."establecimientos"',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionFluidezLectoraFluidez2026',
            fields=[
                ('cantidad_palabras_leidas', models.IntegerField(default=0, null=True)),
                ('pregunta_1', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('pregunta_2', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('pregunta_3', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('pregunta_4', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('pregunta_5', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('pregunta_6', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('NORESPONDE', 'NoResponde')], max_length=10, null=True)),
                ('asistencia', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente')], default='AUSENTE')),
                ('encargado_carga', models.CharField(max_length=9)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='evaluaciones_educativas.alumnofluidez2026')),
            ],
            options={
                'db_table': '"fluidez_2026"."evaluaciones_fluidez_lectora"',
            },
        ),
        migrations.CreateModel(
            name='GradoFluidez2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cueanexo', models.CharField(max_length=9)),
                ('nombre_grado', models.CharField(choices=[('2do Año/Grado', '2do Grado'), ('3er Año/Grado', '3er Grado')], default='2do Año/Grado', max_length=13)),
                ('Establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.establecimientosfluidez2026')),
            ],
            options={
                'db_table': '"fluidez_2026"."grados"',
            },
        ),
        migrations.CreateModel(
            name='SeccionFluidez2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seccion', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('Z', 'Z')], max_length=5)),
                ('turno', models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('DOBLE', 'Doble')], max_length=6)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.gradofluidez2026')),
            ],
            options={
                'db_table': '"fluidez_2026"."secciones"',
                'unique_together': {('seccion', 'grado', 'turno')},
            },
        ),
        migrations.AddField(
            model_name='alumnofluidez2026',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.seccionfluidez2026'),
        ),
    ]
