# Generated by Django 5.2.14 on 2026-06-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0010_alumnofluidez2026_establecimientosfluidez2026_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaTemporalAplicadores',
            fields=[
                ('cuil', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cueanexo', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre_apellido', models.CharField(blank=True, max_length=300, null=True)),
                ('titulacion', models.CharField(blank=True, max_length=255, null=True)),
                ('grado_anio', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado_inscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo_lectivo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"fluidez_2026"."tabla_temporal_aplicadores"',
                'managed': False,
            },
        ),
    ]
