# Generated by Django 5.2.14 on 2026-06-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0012_tablatemporalalumnofluidez2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnofluidez2026',
            name='comunidad_indigena',
            field=models.CharField(blank=True, choices=[('QOM', 'Qom'), ('MOQOIT', 'Moqoit'), ('WICHI', 'Wichí'), ('NINGUNA', 'Ninguna')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='alumnofluidez2026',
            name='discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'Sí, la persona tiene una discapacidad'), ('NO', 'Ninguna')], null=True),
        ),
        migrations.AlterField(
            model_name='alumnofluidez2026',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_educativas.seccionfluidez2026'),
        ),
    ]
