# Generated by Django 5.2.14 on 2026-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0013_alter_alumnofluidez2026_comunidad_indigena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionfluidez2026',
            name='seccion',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('Z', 'Z')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seccionfluidez2026',
            name='turno',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('DOBLE', 'Doble')], max_length=20),
        ),
    ]
