# Generated by Django 5.2.14 on 2026-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0014_alter_seccionfluidez2026_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnofluidez2026',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
