# Generated by Django 5.2.14 on 2026-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_educativas', '0015_alter_alumnofluidez2026_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradofluidez2026',
            name='estado_carga',
            field=models.BooleanField(default=False),
        ),
    ]
